site_name: "Estimation Alignment Hub"
site_description: "A unified system for improving predictability, reducing delivery risk, and aligning expectations across the full software lifecycle."
site_author: "Viktor Jevdokimov, Vilnius, Lithuania"
copyright: "Â© 2025 3in3.dev"

docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - to-pdf:
      output_path: "pdf/eah.pdf"
      cover_subtitle: ""
      toc_level: 1
      ordered_chapter_level: 0

nav:
  - index.md
  - 100-model.md
  - 110-map.md
  - 120-scoring.md
  - 130-diagnostic.md
  - 140-plan.md
  - 200-faq.md
  - 201-faq.md
  - 202-faq.md
  - 203-faq.md
  - 204-faq.md
  - 205-faq.md
  - 206-faq.md
  - 207-faq.md
  - 208-faq.md
  - 209-faq.md
  - 210-faq.md
  - 211-faq.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
